### ISSUE TITLE
Duplicate logbook entries after recent 0.106.x changes

### ISSUE THREAD

**Issue by sfjes** [amelchio/logbook_cache#4]
First, thanks for logbook_cache. It's finally made the Logbook usable! I love it.

A recent fix in 0.106.5 for GPS device_tracker updates spamming the Logbook appears to be only partially functional when logbook_cache is enabled.  Deleting the logbook_cache integration fixes the issue, while re-enabling it causes the problem to appear again.

Background:
After 0.106.0 and before 0.106.5, each GPS device_tracker update was causing its own entry in the Logbook, generating lots of spam. A fix in 0.106.5 suppressed displaying additional Logbook entries unless the state had changed.

With logbook_cache enabled, excess updates (with unchanged state) still appear, but partially suppressed. It seems for each unrelated message shown, another device_tracker update *may* appear, but not necessarily. Sometimes there can be several state engine updates before another message actually appears in the logbook.

Like this:
![Screenshot 2020-03-05 04 10 51](https://user-images.githubusercontent.com/3085494/75980492-68d3b900-5e97-11ea-970f-3c0c110c14f7.png)

I hope that description is clear, let me know if anything needs clarification. Hoping it's an easy fix as I love logbook_cache!  (but also have hundreds or sometimes thousands of device_tracker updates per day)

The PR that caused the initial logbook spam:
https://github.com/home-assistant/core/pull/31551

An issue with screenshots of what the full spam looked like before the 0.106.5 fix:
https://github.com/home-assistant/core/issues/32257

The PR to suppress the Logbook spam:
https://github.com/home-assistant/core/pull/32427

**Comment by amelchio** [comment]
Thanks for reporting this, it is very clear. I will look into the issue.

The logbook groups entries in blocks of 15 minutes which is why you see exactly one entry between 3:15-3:30, another between 3:30-3:45, another between 3:45-4:00, ...

**Comment by amelchio** [comment]
It turns out that the new spam filtering was added to the code path that logbook_cache shortcuts. Adapting would be very hard but fortunately I was able to propose a PR that both cleans up the logbook code in Home Assistant proper and makes it compatible with logbook_cache again: home-assistant/core#32572.

This should be in 0.107.0 or you can probably install the fixed logbook as a custom_component if you want it sooner.

**Comment by sfjes** [comment]
Awesome! Looks good. Thanks!
