### ISSUE TITLE
History? 

### ISSUE THREAD

**Issue by point-4ward** [amelchio/logbook_cache#6]
Not a bug report, this is actually working really well. Just a quick thought / request... 

It's just that now my logbook is working so fast, the history page feels even slower than normal! 

Any chance this concept can be translated translated on to the history component too?

**Comment by amelchio** [comment]
It is a pretty specific hack so I doubt it can be reused. However, I actually don't know since I never dived into the code for the history component.

I am personally using InfluxDB and Grafana for overviews so history performance is not an issue that is bugging me.

**Comment by point-4ward** [comment]
No worries, thanks for looking :slightly_smiling_face:
