### ISSUE TITLE
HACS marks Logbook Cache as critical security risk

### ISSUE THREAD

**Issue by Rohaq** [amelchio/logbook_cache#7]
Not quite sure what's going on here. Screenshots attached (including HACS version)

![Screenshot_20200817-033712](https://user-images.githubusercontent.com/246865/90352416-3bd92400-e03b-11ea-9e31-13f82f9ebb5b.jpg)
![Screenshot_20200817-033743](https://user-images.githubusercontent.com/246865/90352418-3c71ba80-e03b-11ea-9125-e797bc9d5251.jpg)
![Screenshot_20200817-033810](https://user-images.githubusercontent.com/246865/90352419-3d0a5100-e03b-11ea-8c14-04dffdbc265c.jpg)

**Comment by amelchio** [comment]
Thanks for reporting this. The logboog_cache integration was retired in hacs/default#578 because native Home Assistant now is fast enough that it is no longer needed. So the security warning is wrong and honestly upsets me. Maybe @ludeeus knows what's up?

**Comment by ludeeus** [comment]
That looks like a bug in n the HACS frontend.
It some how combined the data for multiple repositories, the text there is for the repository "test/test"

**Comment by amelchio** [comment]
Okay, that can happen. Thanks for fixing it quickly.

**Comment by Rohaq** [comment]
Looks like this fix has gone out in the latest HACS release.

**Comment by amelchio** [comment]
That's good, then we can close this issue.
