### ISSUE TITLE
How can I remove this after it was removed from HACS repositories

### ISSUE THREAD

**Issue by wojciechczyz** [amelchio/logbook_cache#8]
It seems HACS removed it's repository.
How can I remove the left over notification:

Invalid config
The following integrations and platforms could not be set up:

logbook_cache
Please check your config.

Thank you

**Comment by amelchio** [comment]
This is probably from removing the integration in HACS before deleting it in Configuration -> Integrations.

I think you should still be able to remove it somewhere in Configuration but I am not 100% sure.

**Comment by odgregg** [comment]
Yeah. It's still hanging around for me even though every sign of it has been removed. It still shows the following on the HACS page:

![image](https://user-images.githubusercontent.com/5105245/92197220-7b659400-eeb4-11ea-9cbf-bb4e8b8a30dd.png)

**Comment by smcnaught1** [comment]
I have this as well.  Were you able to get it removed?

**Comment by amelchio** [comment]
It seems that I actually have this issue myself with a test install.

I fixed it by stopping Home Assistant, removing `<config>/custom_components/logbook_cache` by hand and then carefully editing `<config>/.storage/hacs.repositories` to remove the `logbook_cache` entry, it looked like below. Make a backup of this file before editing, it is easy to break the JSON formatting by accident, especially by adding or removing a trailing comma.

Then I started Home Assistant again and the warning was gone. I still don't know how this happened in the first place though.

```
        "235453407": {
            "authors": [
                "@amelchio"
            ],
            "category": "integration",
            "description": "Custom component to speed up Home Assistant logbook viewing",
            "domain": null,
            "downloads": 0,
            "full_name": "amelchio/logbook_cache",
            "first_install": false,
            "installed_commit": "62c0309",
            "installed": true,
            "last_commit": "67ac786",
            "last_release_tag": "9",
            "last_updated": "2020-06-26T08:01:57Z",
            "name": null,
            "new": false,
            "repository_manifest": {
                "name": "Logbook Cache",
                "render_readme": true
            },
            "selected_tag": null,
            "show_beta": false,
            "stars": 18,
            "topics": [],
            "version_installed": "8"
        }
```

**Comment by smcnaught1** [comment]
Thanks, resolved the issue!  Much appreciated.
